### ISSUE TITLE
Crahs when try to open

### ISSUE THREAD

**Issue by muhammadarif1** [twenk11k/Wolcano#2]
I can't open the app on my device
```FATAL EXCEPTION: main
Process: com.wolcano.musicplayer.music, PID: 8765
java.lang.RuntimeException: Unable to create application com.wolcano.musicplayer.music.App: g.b.a.d: Could not init DAOConfig
	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4881)
	at android.app.ActivityThread.access$1500(ActivityThread.java:182)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1535)
	at android.os.Handler.dispatchMessage(Handler.java:111)
	at android.os.Looper.loop(Looper.java:218)
	at android.app.ActivityThread.main(ActivityThread.java:5657)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:990)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:785)
Caused by: g.b.a.d: Could not init DAOConfig
	at g.b.a.c.a.<init>(DaoConfig.java:28)
	at g.b.a.b.a(AbstractDaoMaster.java:1)
	at com.wolcano.musicplayer.music.b.a.d.<init>(GreenDaoMaster.java:2)
	at com.wolcano.musicplayer.music.b.a.c.a(DatabaseManager.java:4)
	at com.wolcano.musicplayer.music.App.onCreate(App.java:6)
	at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1017)
	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4878)
	... 9 more
Caused by: java.lang.NoSuchFieldException: TABLENAME
	at java.lang.Class.getField(Class.java:1082)
	at g.b.a.c.a.<init>(DaoConfig.java:3)
	... 15 more```

Android os 5.1

**Comment by twenk11k** [comment]
I have tried with 5.1 device and it's working as expected. Did you build release apk with proguard enabled ? If so, proguard rules are not optimized at the moment.

**Comment by muhammadarif1** [comment]
I DONT HAVE PRO GUARD ON MY PHONE
